// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHoi9ko8J40Br1OYU17588TpfyCdiLAE',
    appId: '1:940558121101:web:f943d7dc8ae3ed83088ac4',
    messagingSenderId: '940558121101',
    projectId: 'flutteredilclima',
    authDomain: 'flutteredilclima.firebaseapp.com',
    databaseURL: 'https://flutteredilclima-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutteredilclima.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Ohgil9IoqzPx_dhdcpdRsD9Czem02n0',
    appId: '1:940558121101:android:b7af40d0eafbca8d088ac4',
    messagingSenderId: '940558121101',
    projectId: 'flutteredilclima',
    databaseURL: 'https://flutteredilclima-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutteredilclima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJUtGsBYNpAkyBzApnV58CYLV6THGCJE4',
    appId: '1:940558121101:ios:656be3c310ab6a75088ac4',
    messagingSenderId: '940558121101',
    projectId: 'flutteredilclima',
    databaseURL: 'https://flutteredilclima-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutteredilclima.appspot.com',
    iosClientId: '940558121101-tqlb46qombc21fihc6dq8sbhplbgcila.apps.googleusercontent.com',
    iosBundleId: 'com.example.edilclimaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJUtGsBYNpAkyBzApnV58CYLV6THGCJE4',
    appId: '1:940558121101:ios:656be3c310ab6a75088ac4',
    messagingSenderId: '940558121101',
    projectId: 'flutteredilclima',
    databaseURL: 'https://flutteredilclima-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutteredilclima.appspot.com',
    iosClientId: '940558121101-tqlb46qombc21fihc6dq8sbhplbgcila.apps.googleusercontent.com',
    iosBundleId: 'com.example.edilclimaApp',
  );
}
